---
title: "InformeRiesgoCrediticio"
author: "Brayan Ortiz, Juan Peña, Thalea Hesse, Juan Falcon, Daniel Espinal"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(purrr)
library(feather)
library(arrow)
library(scorecard)
library(dplyr)    # alternatively, this also loads %>%
library(ggplot2)
library(klaR)
knitr::opts_chunk$set(echo = TRUE)
```

## Lectura de los datos

```{r setup, include=FALSE}

df = arrow::read_feather("datos_juntos.feather")

# Delete cols with more than 50% with NAs
df <- subset(df, select = c(-tot_coll_amt, -tot_cur_bal, -total_rev_hi_lim))

# Solo tienen valores en 0
df <- subset(df, select = c(-collections_12_mths_ex_med, -acc_now_delinq, 
                            -pymnt_plan, -term))

# Valores lógicos se convierten a enteros
df$incumpla <- as.integer(df$incumpla == TRUE)
```

## Separación de datos númericos y categóricos
```{r}
df_num <- subset(df, select = c(-sub_grade, -home_ownership,
                                          -verification_status, -purpose, -addr_state,
                                          -initial_list_status))
```

## Agrupar variables númericas en el dataframe

```{r, include=FALSE}
# Ver los tipos de datos del df
sapply(df_num, class)

bins <- woebin(df_num, y = "incumpla", method = "tree")

options(digits = 3)

# Muestra los bins de la variable X: bins$X
bins$loan_amnt[, c(2, 4, 5, 6, 7, 8)]

# Visualización de los bins de la variable X
woebin_plot(bins, x = "loan_amnt", line_value = "woe")
```

## Aplicar la agrupación para los datos nuevos

```{r, include=FALSE}
df <- woebin_ply(df, bins, to = "bin")
```

## Convertir de datos
```{r}
# Convertir datos númericos a factores
df <- mutate_if(df, sapply(df, is.character), as.factor)

# Convertir datos categóricos a factores
df <- mutate_if(df, sapply(df, is.integer), as.factor)

df <- mutate_if(df, sapply(df, is.logical), as.factor)
```

## División de los datos
```{r, include=FALSE}
tv <- split_df(df, y = "incumpla", ratio = c(0.75, 0.25),
               seed = 42, no_dfs = 2, name_dfs = c("train", "valid"))

train <- tv$train
valid <- tv$valid

```

## Análisis de WOEs

```{r, include=FALSE}


woe_model <- woe(as.factor(train$incumpla) ~ ., data = train)
woe_model$xnew

train_woes <- data.frame(incumpla = train$incumpla, 
                         woe_model$xnew)

valid_woes <- predict(woe_model, subset(valid, select = c(-incumpla)))
valid_woes
# model <- glm(incumpla ~ ., data = train_woes, family = binomial)
summary(model)
```














## ANTES




## Conjunto de prueba y entrenamiento
```{r setup, include=FALSE}
set.seed(27042022) # se fija por reproducibilidad

datos1 <- sample(2, nrow(df2),
                   replace = T,
                   prob = c(0.75, 0.25))
train <- df2[datos1 == 1,]
test <- df2[datos1 == 2,]

train$incumpla[train$incumpla == TRUE] <- 1
train$incumpla[train$incumpla == FALSE] <- 0

test$incumpla[test$incumpla == TRUE] <- 1
test$incumpla[test$incumpla == FALSE] <- 0
```

# Selección de variables
```{r setup, include=FALSE}
# Calculate information values: 
info_values <- iv(train, y = "incumpla", positive = "incumpla|0")
```

```{r setup, include=FALSE}
info_values %>% 
  arrange(info_value) %>% 
  mutate(info_value = round(info_value, 3), variable = factor(variable, levels = variable)) %>% 
  ggplot(aes(variable, info_value)) + 
  geom_col(fill = "#377eb8") + 
  coord_flip() + 
  geom_text(aes(label = info_value), hjust = -.1, size = 5, color = "#377eb8") + 
  labs(title = "Figure 7: Information Value (IV) for All Variables", 
       x = NULL, y = "Information Value (IV)") + 
  scale_y_continuous(expand = c(0, 0), limits = c(0, 0.9)) + 
  theme(panel.grid.major.y = element_blank()) + 
  theme(plot.margin = unit(c(1, 1, 1, 1), "cm"))
```

```{r setup, include=FALSE}
variables_selected_iv <- info_values %>% 
  filter(info_value >= 0.02) %>% 
  pull(1)

df_train_iv <- train %>% select(variables_selected_iv, "incumpla")

bins_var <- woebin(df_train_iv, y = "incumpla", positive = "incumpla|0")

df_train_woe2 <- woebin_ply(df_train_iv, bins_var)
```

```{r, include=FALSE}
model <- glm(incumpla ~ ., data = df_train_woe2)
summary(model)
```

```{r, include=FALSE}
# Convert to binned data frame for test data: 
df_test_iv <- test %>% select(names(df_train_iv))
df_test_woe2 <- woebin_ply(df_test_iv, bins_var)

test_pred2 <- predict(model, df_test_woe2, type = "response")

perf_eva(pred = test_pred2, label = df_test_iv$incumpla,
         type = c("roc"), 
         title = "Test Data")
```
Scorecard
```{r, echo=FALSE}
my_card <- scorecard(bins_var, model)
score1 = scorecard_ply(train, my_card)
```

```{r, echo=FALSE}
library(stringr)
```

```{r, echo=FALSE}
do.call("bind_rows", my_card) %>% 
  slice(-1) %>% 
  select(-breaks, -is_special_values, -count, -count_distr, -neg, -pos, -posprob) %>% 
  mutate_if(is.numeric, function(x) {round(x, 3)}) %>% 
  mutate(bin = bin %>% 
           str_replace_all("\\[", "From ") %>% 
           str_replace_all("\\,", " to ") %>% 
           str_replace_all("\\)", "")) -> iv_for_predictors_point
```

```{r, echo=FALSE}
iv_for_predictors_point %>% 
  knitr::kable(col.names = c("Predictor", "Group", "WOE", "Scorecard", "Bin IV", "Total IV"))
```

